f(wall_following) initial commit
0804robot/Maz--solver pull request #2
Opened 2022-10-07 23:39 UTC by SammyOina

2022-10-09 15:38 UTC, 0x6f736f646f requested changes
Structure it a a library not a project. Here is the reference https://github.com/0804robot/driver/pull/3

2022-10-09 15:38 UTC, 0x6f736f646f commented on .vscode/settings.json
> +{
Remove this

2022-10-09 15:38 UTC, 0x6f736f646f commented on platformio.ini
> +; PlatformIO Project Configuration File
Is this a library of a project?

2022-10-14 19:49 UTC, 0x6f736f646f approved these changes

2022-10-14 21:48 UTC, Mike-Kimani reviewed
If we are solving a maze, we may have a scenario where there's a wall in all directions and need to U-turn. Can we take care of this?

2022-10-15 04:19 UTC, SammyOina commented
> If we are solving a maze, we may have a scenario where there's a wall in all directions and need to U-turn. Can we take care of this?

The current logic only relies on two ultrasonic sensors but we can include that in the next iteration

2022-10-19 10:36 UTC, WashingtonKK approved these changes

2022-10-19 10:36 UTC, merged